---
new_page_extension: md
auto_deploy: false
admin_path: "/static/admin"
webhook_url: 
sections:
- type: directory
  path: content/team
  label: Team
  create: documents
  match: team/*
  templates:
  - authors
- type: directory
  path: content/listings
  label: Listings
  create: documents
  match: "*"
upload_dir: assets/images
public_path: assets/images
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_output_directory: dist
  install_dependencies_command: npm install
  preview_docker_image: forestryio/node:12
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run dev
